### ISSUE TITLE
 Getting Started Database Support

### ISSUE THREAD

**Issue by security101** [DependencyTrack/dependencytrack.org#3]
Hi, 
when following the provided example to configure a MySQL connection (see https://docs.dependencytrack.org/getting-started/database-support/ ) it did not worked out for me with the driver mentioned:

alpine.database.driver.path=~/path/to/mysql-connector-java-5.1.45-bin.jar 

but worked fine when using:

alpine.database.driver.path=~/path/to/mysql-connector-java-8.0.15.jar

Cheers,
Andreas

**Comment by stevespringett** [comment]
Dependency-Track does not support MySQL 8 nor are there plans to. We will be supporting MariaDB 10.x in a future release however.
